### ISSUE TITLE
Add download beta link next to download link on home page

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods-website#2]
Let's add a link to the 2.7 beta post next to the download 2.6.x link.

Either next to it to the right or just below it, but aligned so it doesn't look out of place.

**Comment by sc0ttkclark** [comment]
When 2.7 is released, we can hide the link in the front-page.php template, then enable it when we do 2.8 beta

**Comment by jimtrue** [comment]
Should probably actually route to the Beta Page, since we recommend people use the GitHub Updater

**Comment by sc0ttkclark** [comment]
Yep

**Comment by jimtrue** [comment]
Done. Replaced those buttons with CSS gradient buttons.
